// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: upgrade_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeUserPlan = `-- name: UpgradeUserPlan :exec
UPDATE users
SET is_chirpy_red = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpgradeUserPlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeUserPlan, id)
	return err
}
